server:
  port: 8080
spring:
  # datasource config
  datasource:
    url: jdbc:mysql://192.168.71.128:3307/partner_search
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    timeout: 2592000  # session失效时间
    store-type: redis
  # redis config
  redis:
    host: 192.168.71.128
    port: 6379
    password: 123456
    database: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
